### PR TITLE
Merge pull request #1 from arpitchauhan/master

### PR DESCRIPTION
**Pull request by adiflexs007**
Hi,

It would be great if you could add me as a contributor. I need to show it as a proof in my college that I did this as minor project.

Regards,
Aditya Pandey

### CODE REVIEW

**Comment by arpitchauhan** [comment]
Ok, I'll make the necessary changes.

**Comment by FalloutX** [comment]
You also need to Delete this pull request. May be thats not possible :stuck_out_tongue:

**Comment by arpitchauhan** [comment]
Oh hahahaha. It must be visible to others right now.

Best,
Arpit

**Comment by arpitchauhan** [comment]
I don't think I can delete it. Maybe, Aditya will need to do that.

Best,
Arpit

**Pull request closed without merging**
